Document: soci
Title: Debian soci Manual
Author: <insert document author here>
Abstract: This manual describes what soci is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/soci/soci.sgml.gz

Format: postscript
Files: /usr/share/doc/soci/soci.ps.gz

Format: text
Files: /usr/share/doc/soci/soci.text.gz

Format: HTML
Index: /usr/share/doc/soci/html/index.html
Files: /usr/share/doc/soci/html/*.html
